### PR TITLE
Rebase to 1.2.7

### PR DESCRIPTION
**Pull request by 13r0ck**
Rebase to version 1.2.7

Required by: https://github.com/pop-os/alsa-ucm-conf/pull/2

### CODE REVIEW

**Comment by XV-02** [comment]
This is working for Mira-B1. Currently ensuring no regressions elsewhere.

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — CHANGES_REQUESTED** [review]
Walking back my approval because I believe files in debian/ were committed but should not be. Run `fakeroot debian/rules clean` to ensure all temporary files are removed.

**Comment by 13r0ck** [comment]
@jackpot51 does that look better?

**Review by XV-02 — APPROVED** [review]
In concert with https://github.com/pop-os/alsa-ucm-conf/pull/2 and https://github.com/pop-os/linux/pull/146, this is both working, and not inducing any detectable regressions in other hardware.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
